csi level.csx 1.level.txt IntoTheBlaze\Levels\1.level
csi level.csx 2.level.txt IntoTheBlaze\Levels\2.level
csi level.csx 3.level.txt IntoTheBlaze\Levels\3.level
csi level.csx 4.level.txt IntoTheBlaze\Levels\4.level
csi level.csx 5.level.txt IntoTheBlaze\Levels\5.level
csi level.csx 6.level.txt IntoTheBlaze\Levels\6.level
csi level.csx 7.level.txt IntoTheBlaze\Levels\7.level
csi level.csx 8.level.txt IntoTheBlaze\Levels\8.level
csi level.csx 9.level.txt IntoTheBlaze\Levels\9.level
csi level.csx 10.level.txt IntoTheBlaze\Levels\10.level
csi level.csx 11.level.txt IntoTheBlaze\Levels\11.level
csi level.csx 12.level.txt IntoTheBlaze\Levels\12.level
csi level.csx 13.level.txt IntoTheBlaze\Levels\13.level
csi level.csx 14.level.txt IntoTheBlaze\Levels\14.level
csi level.csx 15.level.txt IntoTheBlaze\Levels\15.level
csi level.csx 16.level.txt IntoTheBlaze\Levels\16.level
